# Generated by Django 5.1 on 2024-08-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('post', 'user')},
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='posts.post'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['post', 'user'], name='posts_ratin_post_id_02fb24_idx'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rated_at',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
